apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: java-app
  template:
    metadata:
      labels:
        service: java-app
    spec:
      containers:
        - image: ghcr.io/polina2/tinkoff-java-course-2023/scrapper:hw8
          name: scrapper
          ports:
            - containerPort: 8080