app:
  test: it works
  scheduler:
    interval: 10000
  gitBaseUrl: https://api.github.com
  stackoverflowBaseUrl: https://api.stackexchange.com
  botBaseUrl: http://localhost:8180
  database-access-type: jdbc

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false
  jpa:
    show-sql: true
