app:
  test: it works
  token: ${TOKEN}
  baseUrl: http://localhost:8080

server:
  port: 8180

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: bot

management:
  server:
    port: 8181
  endpoints:
    web:
      base-path: /
      exposure:
        include: "health,info,prometheus"
      path-mapping:
        prometheus: metrics
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}