app:
  test: it works
  token: ${TOKEN}
  baseUrl: http://localhost:8080
  rabbitmq:
    exchange: directExchange
    queue: queue
    routingKey: directRoutingKey

server:
  port: 8180

springdoc:
  swagger-ui:
    path: /swagger-ui
