name: bot
on:
  push:
    paths:
      - 'bot/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          java-version: 19
      - name: build with maven
        run: mvn package -pl bot -am
