name: scrapper
on:
  push:
    paths-ignore:
      - 'project/bot/**'
      - '**/bot.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'temurin'
          cache: maven
      - name: build with maven
        run: |
          cd project
          mvn package -pl scrapper -am
      - name: build docker image
        run: docker build -f scrapper.Dockerfile -t scrapper .
      - name: log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.event.repository.name }}/scrapper:latest